blueprint:
  name: Device ready created by R0g3rT
  description: "# Device ready / Gerät fertig   
  
    Version 1.1  2025-12-25
    
    Detects device finished state via power sensor. Prevents standby-trigger spam by using a selectable helper.
    Auto-selects DE/EN messages based on Home Assistant UI language (sensor.language / sensor.system_language).
    Optional TTS output with automatic language mapping.

    Erkennt über einen Stromsensor ob das Gerät fertig ist. Verhindert im Standby Trigger-Spam durch die Verwendung eines auswählbaren Hilfsprogramms.  
    Wählt DE/EN-Meldungen automatisch basierend auf der Sprache der Home Assistant-Benutzeroberfläche aus (sensor.language / sensor.system_language).  
    Optionale TTS-Ausgabe mit automatischer Sprachzuordnung.

    **Hinweis:** * **Die Nutzung erfolgt auf eigene Gefahr!**
    
    **Information:** * **You use this at your own risk!**
    "
  domain: automation
  source_url: https://github.com/R0g3rT/home-assistant-blueprints/blob/main/Device_ready.yaml

  input:
    power_sensor:
      name: Power sensor / Leistungssensor
      selector:
        entity:
          domain: sensor

    running_power:
      name: Running power threshold (W) / Leistung während Betrieb (W)
      default: 15
      selector:
        number:
          min: 5
          max: 3000
          unit_of_measurement: W

    running_for:
      name: Running must persist / Betrieb muss anliegen
      default:
        minutes: 2
      selector:
        duration:

    finished_power:
      name: Finished power threshold (W) / Leistung nach Ende (W)
      default: 5
      selector:
        number:
          min: 0
          max: 20
          unit_of_measurement: W

    finished_duration:
      name: Finished must persist / Ende muss anliegen
      default:
        minutes: 5
      selector:
        duration:

    run_helper:
      name: Helper "device ran" / Helper „Gerät lief“
      description: Set to ON when device started; required to avoid standby false positives.
      selector:
        entity:
          domain: input_boolean

    notify_time_start:
      name: Notification start time / Startzeit Benachrichtigungen
      default: "06:00:00"
      selector:
        time:

    notify_time_end:
      name: Notification end time / Endzeit Benachrichtigungen
      default: "20:00:00"
      selector:
        time:


    # -----------------------
    # Notifications (text)
    # -----------------------
    notify_all:
      name: Notify targets (text) / Benachrichtigung (Text)
      selector:
        target:

    notify_special:
      name: Notify targets special (text, optional) / Extra Text (optional)
      default: {}
      selector:
        target:

    message_all_de:
      name: Message DE (all)
      default: "Das Gerät ist fertig und kann ausgeräumt werden."
      selector:
        text:

    message_all_en:
      name: Message EN (all)
      default: "The device has finished and can be unloaded."
      selector:
        text:

    message_special_de:
      name: Message DE (special, optional)
      default: ""
      selector:
        text:

    message_special_en:
      name: Message EN (special, optional)
      default: ""
      selector:
        text:

    # -----------------------
    # TTS (optional)
    # -----------------------
    tts_enabled:
      name: Enable TTS / TTS aktivieren
      default: false
      selector:
        boolean:

    tts_service:
      name: TTS service (e.g. tts.google_translate_say / tts.speak)
      description: >
        Example: tts.google_translate_say (legacy) or tts.speak (newer).
        Must match your HA setup.
      default: ""
      selector:
        text:

    tts_media_player:
      name: Media player(s) for TTS
      default: {}
      selector:
        target:
          entity:
            domain: media_player

    tts_voice_de:
      name: Voice DE (optional)
      description: Leave empty if your TTS integration doesn't support voice parameter.
      default: ""
      selector:
        text:

    tts_voice_en:
      name: Voice EN (optional)
      description: Leave empty if your TTS integration doesn't support voice parameter.
      default: ""
      selector:
        text:

mode: single

variables:

   notify_allowed: >-
    {% set now_t = now().strftime('%H:%M:%S') %}
    {% set start = blueprint.inputs.notify_time_start %}
    {% set end = blueprint.inputs.notify_time_end %}
    {% if start < end %}
      {{ start <= now_t <= end }}
    {% else %}
      {{ now_t >= start or now_t <= end }}
    {% endif %}

  # HA language entity varies by version/installation. We try both.
  ha_lang: >-
    {% set l = states('sensor.language') %}
    {% if l in ['unknown','unavailable','none','None',''] %}
      {{ states('sensor.system_language') }}
    {% else %}
      {{ l }}
    {% endif %}
  # Normalize: 'de-DE' -> 'de', 'en-US' -> 'en'
  lang2: "{{ (ha_lang or 'en')[:2] | lower }}"
  # Choose messages
  msg_all: >-
    {% if lang2 == 'de' %}{{ iif(true, blueprint.inputs.message_all_de, '') }}{% else %}{{ iif(true, blueprint.inputs.message_all_en, '') }}{% endif %}
  msg_special: >-
    {% if lang2 == 'de' %}{{ iif(true, blueprint.inputs.message_special_de, '') }}{% else %}{{ iif(true, blueprint.inputs.message_special_en, '') }}{% endif %}
  # TTS language codes (common)
  tts_lang: >-
    {% if lang2 == 'de' %}de-DE{% else %}en-US{% endif %}
  tts_voice: >-
    {% if lang2 == 'de' %}{{ iif(true, blueprint.inputs.tts_voice_de, '') }}{% else %}{{ iif(true, blueprint.inputs.tts_voice_en, '') }}{% endif %}

trigger:
  - platform: numeric_state
    entity_id: !input power_sensor
    above: !input running_power
    for: !input running_for
    id: started

  - platform: numeric_state
    entity_id: !input power_sensor
    below: !input finished_power
    for: !input finished_duration
    id: finished

action:
  - choose:
      # ----------------------
      # Start detected
      # ----------------------
      - conditions:
          - condition: trigger
            id: started
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: !input run_helper

      # ----------------------
      # Finished detected (only if it ran)
      # ----------------------
      - conditions:
          - condition: trigger
            id: finished
          - condition: state
            entity_id: !input run_helper
            state: "on"
          - condition: template
            value_template: "{{ notify_allowed }}"

        sequence:
          # Text notifications
          - service: notify.send_message
            target: !input notify_all
            data:
              message: "{{ msg_all }}"

          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ (msg_special | default('')) | trim != '' }}"
                sequence:
                  - service: notify.send_message
                    target: !input notify_special
                    data:
                      message: "{{ msg_special }}"

          # Optional TTS
          - choose:
              - conditions:
                  - condition: template
                    value_template: >-
                      {{ (blueprint.inputs.tts_enabled | default(false)) and
                         (blueprint.inputs.tts_service | default('') | trim != '') and
                         (blueprint.inputs.tts_media_player is not none) }}
                sequence:
                  # Works for most common services:
                  # - tts.google_translate_say: data: { entity_id, message, language }
                  # - tts.speak: data: { media_player_entity_id, message, language, options: { voice } }
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ blueprint.inputs.tts_service | trim == 'tts.speak' }}"
                        sequence:
                          - service: tts.speak
                            data:
                              media_player_entity_id: >-
                                {% if blueprint.inputs.tts_media_player.entity_id is defined %}
                                  {{ blueprint.inputs.tts_media_player.entity_id }}
                                {% else %}
                                  {{ [] }}
                                {% endif %}
                              message: "{{ msg_all }}"
                              language: "{{ tts_lang }}"
                              options: >-
                                {% set v = (tts_voice | default('') | trim) %}
                                {% if v != '' %}
                                  {{ dict(voice=v) }}
                                {% else %}
                                  {{ dict() }}
                                {% endif %}
                      - conditions:
                          - condition: template
                            value_template: "{{ blueprint.inputs.tts_service | trim != 'tts.speak' }}"
                        sequence:
                          - service: "{{ blueprint.inputs.tts_service | trim }}"
                            data:
                              entity_id: >-
                                {% if blueprint.inputs.tts_media_player.entity_id is defined %}
                                  {{ blueprint.inputs.tts_media_player.entity_id }}
                                {% else %}
                                  {{ [] }}
                                {% endif %}
                              message: "{{ msg_all }}"
                              language: "{{ tts_lang }}"
                              # Some services ignore this safely:
                              voice: "{{ (tts_voice | default('') | trim) }}"
            default: []

          # Reset helper so it triggers only once per cycle
          - service: input_boolean.turn_off
            target:
              entity_id: !input run_helper
